project:
  type: website
  output-dir: "docs"
  
execute:
  freeze: auto  # re-render only when source changes
  
website:
  title: "Interactive Data Viz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About"
    right:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/ucldw26-interactive-data-viz

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    page-layout: full
    toc: true



